FROM node:20-slim


RUN apt-get update && \
apt-get install -y libreoffice wget fonts-dejavu poppler-utils && \
rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN mkdir -p uploads output
EXPOSE 3000
CMD ["node", "server.js"]